service: service-with-requirements-layer

provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      description: Python requirements lambda layer
      allowedAccounts:
        - '*'